### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by gabrielpra1** [gabrielpra1/crudry#17]

**Comment by jungrafael** [comment]
It may make sense to implement Travis as a Continuous Integration Tool. It is pretty standard in Open Source Elixir projects: https://docs.travis-ci.com/

**Comment by gabrielpra1** [comment]
Yeah, that's the idea 😄

**Comment by gabrielpra1** [comment]
Closed by https://github.com/gabrielpra1/crudry/pull/29
