### ISSUE TITLE
Deal with inexistent ID on context

### ISSUE THREAD

**Issue by gabrielpra1** [gabrielpra1/crudry#19]
Decide how to deal with update/delete by id when there is not record with that ID.

- [ ] Return error
- [ ] Return nil
- [ ] Let it crash

**Comment by jungrafael** [comment]
I think we should follow the `Ecto` standards: bang functions like `update!` should crash and `update` returns an error `{:error, error}`.

**Comment by jungrafael** [comment]
The format of the `error` returned is a good question.

**Comment by gabrielpra1** [comment]
`Repo.update` returns https://hexdocs.pm/ecto/Ecto.StaleEntryError.html when the changeset contains an ID that is not in the DB, but I wouldn't expect a function without bang to raise. I was thinking we could return something like `{:error, :not_found}`?

**Comment by gabrielpra1** [comment]
It now returns a changeset error, following [Repo.insert](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2) pattern when `:stale_error_field` is provided
