### ISSUE TITLE
Feature Request: Generate _exists? functions

### ISSUE THREAD

**Issue by rafaelofreitas** [gabrielpra1/crudry#48]
Sometimes we just need to check if a data exists to continue with our business logic, something like:

```elixir
 def my_schema_exists?(id) do
   case Repo.get(MySchema, id) do
     %MySchema{} -> true
     nil -> false
   end
 end
```

**Comment by jotaviobiondo** [comment]
Nice! 

A improvement here is that we can use `Repo.exists?/2` with a custom query instead of `Repo.get/2`
